import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import "./style.css";
import ThemeConfig from "@/styles/theme";
import Header from "@/components/header";
import { Grid } from "@mui/material";
import GoogleAuthProvider from "@/providers/authProvider/googleService";
export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Suspense>
          <ThemeConfig>
            <GoogleAuthProvider>
              <Header />
              <Grid container spacing={2} marginTop={1}>
                <Grid item xs={3}>
                  {/* <Sidebar /> */}
                  Left Layout
                </Grid>
                <Grid item xs={6}>
                  <>{children}</>
                </Grid>
                <Grid item xs={3}>
                  {/* <Sidebar /> */}
                  Right Layout
                </Grid>
              </Grid>
            </GoogleAuthProvider>
          </ThemeConfig>
        </Suspense>
      </body>
    </html>
  );
}
